/*
# Part 2: auto-assign table_number

## Summary
Part 1 required the admin to type a table number by hand. Part 2 asks for
automatic sequential numbering ("Add Table" -> Table 1, then Table 2, ...)
so this converts `tables.table_number` into a database-generated identity
column. Doing this at the database level (rather than computing MAX()+1 in
the browser) is what makes it safe under concurrent admin usage — the
sequence increment is atomic, so two rapid "Add Table" clicks can never be
assigned the same number.

This migration only touches the `tables` table, which is itself new (added
in Part 1) — nothing from the original POS is affected.

Idempotent: safe to re-run. If `table_number` is already an identity
column (e.g. this migration already ran), the ADD GENERATED step is
skipped. The sequence is always re-synced to MAX(table_number)+1, which is
harmless to repeat and correctly accounts for any tables added manually in
Part 1 testing before this upgrade.
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    WHERE c.relname = 'tables'
      AND a.attname = 'table_number'
      AND a.attidentity <> ''
  ) THEN
    ALTER TABLE tables ALTER COLUMN table_number ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Re-sync the identity sequence to continue after the highest existing
-- table number, so the next auto-assigned number is always MAX + 1
-- regardless of any table numbers entered manually before this upgrade.
SELECT setval(
  pg_get_serial_sequence('tables', 'table_number'),
  GREATEST(COALESCE((SELECT MAX(table_number) FROM tables), 0), 0) + 1,
  false
);
